# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zc6W1RJqkaJY1vHNELzMHrsti_f43qTd
"""

# Ask the user to enter their first name and store the answer in the first_name variable.
first_name = input("Enter your first name: ")  # The input() function lets the user type their first name.

# Ask the user to enter their last name and store the answer in the last_name variable.
last_name = input("Enter your last name: ")  # The input() function lets the user type their last name.

# Combine the first name and last name with a space between them and display the complete name.
print(first_name + " " + last_name)  # The print() function displays the user's full name on the screen.
